models:
  model_A:
    model_name: "openai/gpt-oss-20b"
    temperature: 0.6
    top_p: 0.95
    top_k: 40
    seed: 42
    reasoning: false
    api_key: "" 
    base_url: ""  

  model_B:
    model_name: "openai/gpt-oss-120b"
    temperature: 0.6
    top_p: 0.95
    top_k: 40
    seed: 42
    reasoning: true
    api_key: ""
    base_url: ""
  
  model_C:
    model_name: "qwen/qwen3-next-80b-a3b-thinking"
    temperature: 0.6
    top_p: 0.95
    top_k: 40
    seed: 42
    reasoning: true
    api_key: ""
    base_url: ""
  

    # model_D:
    # model_name: "minimaxai/minimax-m2"
    # temperature: 0.6
    # top_p: 0.95
    # top_k: 40
    # seed: 42
    # reasoning: true
    # api_key: ""
    # base_url: ""


